
import React, { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { useToast } from "@/components/ui/use-toast";
import { Form } from "@/components/ui/form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { ArrowLeft } from "lucide-react";
import { 
  getContentById, 
  createContent, 
  updateContent,
  getAvailableTags,
  generateSlug,
  ContentItem
} from "@/lib/services/contentService";
import ContentMainFields from "./ContentMainFields";
import ContentTypeSelector from "./ContentTypeSelector";
import ContentStatusSelector from "./ContentStatusSelector";
import TagInput from "../TagInput";
import ImageUploader from "./ImageUploader";
import ClientInfoFields from "./ClientInfoFields";
import ContentFormActions from "./ContentFormActions";
import { ContentFormValues } from "./ContentFormTypes";
import { FormField, FormItem, FormLabel, FormControl, FormDescription, FormMessage } from "@/components/ui/form";
import { Input } from "@/components/ui/input";

const formSchema = z.object({
  title: z.string().min(5, "Title must be at least 5 characters"),
  subtitle: z.string().min(10, "Subtitle must be at least 10 characters"),
  content: z.string().min(50, "Content must be at least 50 characters"),
  category: z.enum(["blog", "case-study"]),
  tags: z.array(z.string()).min(1, "At least one tag is required"),
  clientName: z.string().optional(),
  clientIndustry: z.string().optional(),
  featuredImage: z.string().optional(),
  status: z.enum(["draft", "published"]),
  slug: z.string().optional()
});

const ContentForm: React.FC = () => {
  const { id } = useParams();
  const isEditing = Boolean(id);
  const [isLoading, setIsLoading] = useState(isEditing);
  const { toast } = useToast();
  const navigate = useNavigate();
  const [previewImage, setPreviewImage] = useState<string | null>(null);
  const [availableTags, setAvailableTags] = useState<string[]>([]);
  const [autoGeneratedSlug, setAutoGeneratedSlug] = useState<string>("");

  const defaultTags = [
    "SEO", "Digital Marketing", "Social Media", "PPC", 
    "Content Marketing", "Email Marketing", "Analytics", 
    "Web Development", "Mobile Development", "E-commerce",
    "Conversion", "ROI", "Strategy", "Branding"
  ];

  const form = useForm<ContentFormValues>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      title: "",
      subtitle: "",
      content: "",
      category: "blog",
      tags: [],
      clientName: "",
      clientIndustry: "",
      featuredImage: "",
      status: "draft",
      slug: ""
    }
  });

  // Generate slug when title changes
  const title = form.watch("title");
  useEffect(() => {
    if (title && !isEditing) {
      const slug = generateSlug(title);
      setAutoGeneratedSlug(slug);
    }
  }, [title, isEditing]);

  useEffect(() => {
    const authData = localStorage.getItem("touchpointe_auth");
    
    if (!authData) {
      navigate("/admin");
      return;
    }
    
    loadTags();
    
    if (isEditing && id) {
      fetchContent(id);
    }
  }, [isEditing, id, navigate]);

  const loadTags = async () => {
    try {
      const tags = await getAvailableTags();
      const allTags = [...new Set([...defaultTags, ...tags])];
      setAvailableTags(allTags);
    } catch (error) {
      console.error("Error loading tags:", error);
      setAvailableTags(defaultTags);
    }
  };

  const fetchContent = async (contentId: string) => {
    setIsLoading(true);
    
    try {
      const contentItem = await getContentById(contentId);
      
      if (contentItem) {
        form.reset({
          title: contentItem.title,
          subtitle: contentItem.subtitle,
          content: contentItem.content || "",
          category: contentItem.category,
          tags: contentItem.tags,
          status: contentItem.status,
          clientName: contentItem.clientName,
          clientIndustry: contentItem.clientIndustry,
          featuredImage: contentItem.featuredImage,
          slug: contentItem.slug
        });
        
        if (contentItem.featuredImage) {
          setPreviewImage(contentItem.featuredImage);
        }
      } else {
        toast({
          title: "Content not found",
          description: "The requested content could not be found",
          variant: "destructive",
        });
        navigate("/admin/content");
      }
    } catch (error) {
      toast({
        title: "Error loading content",
        description: "Could not load the content for editing",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const onSubmit = async (values: ContentFormValues) => {
    setIsLoading(true);
    
    // Use auto-generated slug if none is provided
    if (!values.slug && autoGeneratedSlug) {
      values.slug = autoGeneratedSlug;
    }
    
    try {
      if (isEditing && id) {
        const updatedContent = await updateContent(id, {
          ...values,
          publishedAt: values.status === "published" ? new Date().toISOString() : null,
        });
        
        if (updatedContent) {
          toast({
            title: values.status === "published" ? "Content updated and published!" : "Draft updated",
            description: `Your ${values.category} has been updated.`,
          });
          navigate("/admin/content");
        } else {
          throw new Error("Failed to update content");
        }
      } else {
        // Create new content
        const newContent = await createContent({
          title: values.title,
          subtitle: values.subtitle,
          content: values.content,
          category: values.category,
          tags: values.tags,
          status: values.status,
          publishedAt: values.status === "published" ? new Date().toISOString() : null,
          featuredImage: values.featuredImage,
          clientName: values.clientName,
          clientIndustry: values.clientIndustry,
          slug: values.slug
        });
        
        if (newContent) {
          toast({
            title: values.status === "published" ? "Content published!" : "Draft saved",
            description: `Your ${values.category} has been ${values.status === "published" ? "published" : "saved as a draft"}.`,
          });
          navigate("/admin/content");
        } else {
          throw new Error("Failed to create content");
        }
      }
    } catch (error) {
      console.error("Error saving content:", error);
      toast({
        title: "Error saving content",
        description: "An error occurred while saving your content. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const watchCategory = form.watch("category");

  return (
    <div className="max-w-7xl mx-auto">
      <div className="flex items-center justify-between mb-12">
        <div className="flex items-center gap-6">
          <Button 
            variant="ghost" 
            size="icon"
            onClick={() => navigate("/admin/content")}
            className="h-12 w-12 rounded-xl bg-white/[0.05] border border-white/[0.1] hover:bg-blue-600 hover:text-white transition-all shadow-xl"
          >
            <ArrowLeft className="h-5 w-5" />
          </Button>
          <div>
            <div className="text-[10px] font-black text-blue-400 uppercase tracking-[0.2em] mb-1 ml-0.5">Content Orchestration</div>
            <h1 className="text-3xl md:text-5xl font-black text-white uppercase tracking-tight">
              {isEditing ? "Edit Asset" : "New Asset"}
            </h1>
          </div>
        </div>
      </div>
      
      {isLoading ? (
        <div className="flex flex-col justify-center items-center min-h-[500px] bg-white/[0.02] rounded-[3rem] border border-white/[0.05] backdrop-blur-3xl">
          <div className="animate-spin h-12 w-12 border-4 border-blue-500 rounded-full border-t-transparent shadow-[0_0_30px_rgba(59,130,246,0.5)] mb-6"></div>
          <p className="text-xs font-black text-gray-400 uppercase tracking-widest">Reconfiguring Neural Pathways...</p>
        </div>
      ) : (
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-12">
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-12">
              <div className="lg:col-span-2 space-y-12">
                <ContentMainFields form={form} />
                
                <div className="bg-white/[0.03] backdrop-blur-md p-10 rounded-[2rem] border border-white/[0.08] shadow-2xl">
                  <FormField
                    control={form.control}
                    name="slug"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-gray-400 font-black uppercase tracking-widest text-[10px] ml-1">URL Architecture (Slug)</FormLabel>
                        <FormControl>
                          <div className="relative group">
                            <div className="absolute inset-y-0 left-0 pl-6 flex items-center pointer-events-none text-gray-600 font-bold text-sm">/content/</div>
                            <Input 
                              placeholder={autoGeneratedSlug || "proxima-voyage-2026"} 
                              className="h-14 bg-white/[0.05] border-white/[0.08] text-white placeholder:text-gray-700 rounded-2xl focus:ring-1 focus:ring-blue-500/50 transition-all font-mono text-sm pl-[84px]"
                              {...field} 
                            />
                          </div>
                        </FormControl>
                        <FormDescription className="text-[10px] text-gray-500 font-bold uppercase tracking-tight mt-3 ml-1">
                          Immutable identifier for search algorithms. Leave blank for auto-generation.
                        </FormDescription>
                        <FormMessage className="text-xs font-bold text-red-400" />
                      </FormItem>
                    )}
                  />
                </div>
              </div>
              
              <div className="space-y-12">
                <ContentTypeSelector form={form} />
                
                <div className="bg-white/[0.03] backdrop-blur-md p-6 rounded-2xl border border-white/[0.08]">
                  <FormField
                    control={form.control}
                    name="tags"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-gray-400 font-black uppercase tracking-widest text-[10px] ml-1">Taxonomy Hub</FormLabel>
                        <FormControl>
                          <TagInput
                            availableTags={availableTags}
                            selectedTags={field.value || []}
                            onChange={field.onChange}
                          />
                        </FormControl>
                        <FormDescription className="text-[10px] text-gray-500 font-bold uppercase tracking-tight mt-3 ml-1">
                          Categorize your asset for retrieval systems.
                        </FormDescription>
                        <FormMessage className="text-xs font-bold text-red-400" />
                      </FormItem>
                    )}
                  />
                </div>
                
                <ClientInfoFields form={form} visible={watchCategory === "case-study"} />
                
                <ImageUploader 
                  form={form} 
                  previewImage={previewImage}
                  setPreviewImage={setPreviewImage}
                />
                
                <ContentStatusSelector form={form} />
              </div>
            </div>
            
            <ContentFormActions 
              isLoading={isLoading} 
              status={form.watch("status")} 
            />
          </form>
        </Form>
      )}
    </div>
  );
};

export default ContentForm;
