// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfmdamokviyveimfdasx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmbWRhbW9rdml5dmVpbWZkYXN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMzM0MDAsImV4cCI6MjA1NzgwOTQwMH0.iethAOhGdFQPvRdneUK7jjzb4LAak28z7UrH5G4Kydc";

// Import the supabase client like this:
// import { supabase } from "@/lib/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);